from .get_token import get_bot_token
from .add_skillbox_chat import add_new_skillbox_chat
from .get_list_admins import get_bot_admins
from .add_admin import add_new_admin
from .get_password import get_bot_password
from .set_password import set_bot_password
from .del_admin import del_admin
from .get_list_user_group import get_list_user_group
from .set_moderator_chat import set_moderator_chat
from .get_list_moder_group import get_list_moder_group
from .del_moder import dell_moderator_chat
from .check_moder_chat import check_moder_chat
from .set_multiplicity_numbers import set_multiplicity_numbers
from .get_numbers import get_numbers
from .add_user import add_user
from .get_moder import get_moder
from .check_student import check_student
from .get_count_user import get_count_user